export interface TransactionItem {
  id: string
  transactionId: string
  type: string
  amount: string
  isPositive: boolean
  date: string
  status: 'Completed' | 'Pending' | 'Failed' | 'Disputed' | 'Refunded'
  relatedTo: string
  description?: string
  paymentMethod?: string
}

export const MOCK_TRANSACTIONS: TransactionItem[] = [
  {
    id: '1',
    transactionId: 'TXN001',
    type: 'Booking Payment',
    amount: '+$5,000',
    isPositive: true,
    date: '2025-01-02',
    status: 'Completed',
    relatedTo: 'Booking #BK-10234',
    description: 'Event center booking for corporate event',
    paymentMethod: 'Credit Card',
  },
  {
    id: '2',
    transactionId: 'TXN002',
    type: 'Subscription Payment',
    amount: '+$99',
    isPositive: true,
    date: '2025-01-01',
    status: 'Completed',
    relatedTo: 'Grand Ballroom Hall',
    description: 'Monthly Professional Plan subscription renewal',
    paymentMethod: 'Bank Transfer',
  },
  {
    id: '3',
    transactionId: 'TXN003',
    type: 'Withdrawal',
    amount: '-$2,500',
    isPositive: false,
    date: '2024-12-30',
    status: 'Completed',
    relatedTo: 'John Smith',
    description: 'Payout request to vendor bank account',
    paymentMethod: 'Direct Deposit',
  },
  {
    id: '4',
    transactionId: 'TXN004',
    type: 'Refund',
    amount: '+$500',
    isPositive: true,
    date: '2024-12-28',
    status: 'Pending',
    relatedTo: 'Booking #BK-10120',
    description: 'Cancellation refund processing',
    paymentMethod: 'Credit Card',
  },
  {
    id: '5',
    transactionId: 'TXN005',
    type: 'Booking Payment',
    amount: '+$3,500',
    isPositive: true,
    date: '2024-12-27',
    status: 'Completed',
    relatedTo: 'Booking #BK-10118',
    description: 'Catering package booking fee',
    paymentMethod: 'Debit Card',
  },
  {
    id: '6',
    transactionId: 'TXN006',
    type: 'Withdrawal',
    amount: '-$1,800',
    isPositive: false,
    date: '2024-12-25',
    status: 'Failed',
    relatedTo: 'Emily Davis',
    description: 'Platform payout transaction failed due to bank verification',
    paymentMethod: 'Direct Deposit',
  },
  {
    id: '7',
    transactionId: 'TXN007',
    type: 'Subscription Payment',
    amount: '+$49',
    isPositive: true,
    date: '2024-12-20',
    status: 'Completed',
    relatedTo: 'Taste of Home Catering',
    description: 'Basic Plan monthly fee',
    paymentMethod: 'Credit Card',
  },
  {
    id: '8',
    transactionId: 'TXN008',
    type: 'Booking Payment',
    amount: '+$8,000',
    isPositive: true,
    date: '2024-12-15',
    status: 'Pending',
    relatedTo: 'Booking #BK-10099',
    description: 'Wedding reception hall deposit',
    paymentMethod: 'Bank Wire',
  },
  {
    id: '9',
    transactionId: 'TXN009',
    type: 'KYC Payment',
    amount: '+$25',
    isPositive: true,
    date: '2025-01-10',
    status: 'Completed',
    relatedTo: 'Downtown Event Space',
    description: 'Provider KYC verification processing fee',
    paymentMethod: 'Credit Card',
  },
  {
    id: '10',
    transactionId: 'TXN010',
    type: 'Certification Payment',
    amount: '+$50',
    isPositive: true,
    date: '2025-01-12',
    status: 'Completed',
    relatedTo: 'Grand Ballroom Hall',
    description: 'Verified venue badge renewal fee',
    paymentMethod: 'Credit Card',
  },
  {
    id: '11',
    transactionId: 'TXN011',
    type: 'Featured Plan Payment',
    amount: '+$199',
    isPositive: true,
    date: '2025-01-15',
    status: 'Completed',
    relatedTo: 'Gourmet Delights Catering',
    description: 'Homepage featured listing promotion',
    paymentMethod: 'Credit Card',
  },
  {
    id: '12',
    transactionId: 'TXN012',
    type: 'Booking Payment',
    amount: '+$4,200',
    isPositive: true,
    date: '2025-01-18',
    status: 'Disputed',
    relatedTo: 'Booking #BK-10245',
    description: 'Customer chargeback dispute opened',
    paymentMethod: 'Credit Card',
  },
  {
    id: '13',
    transactionId: 'TXN013',
    type: 'Booking Payment',
    amount: '+$1,500',
    isPositive: true,
    date: '2025-01-20',
    status: 'Refunded',
    relatedTo: 'Booking #BK-10250',
    description: 'Full refund issued for cancelled event',
    paymentMethod: 'Debit Card',
  },
  {
    id: '14',
    transactionId: 'TXN014',
    type: 'Booking Payment',
    amount: '+$6,800',
    isPositive: true,
    date: '2025-01-22',
    status: 'Completed',
    relatedTo: 'Booking #BK-10255',
    description: 'Corporate gala dinner hall payment',
    paymentMethod: 'Credit Card',
  },
  {
    id: '15',
    transactionId: 'TXN015',
    type: 'Subscription Payment',
    amount: '+$999',
    isPositive: true,
    date: '2025-01-25',
    status: 'Completed',
    relatedTo: 'Riverside Convention Center',
    description: 'Annual Enterprise Plan subscription fee',
    paymentMethod: 'Bank Transfer',
  },
]
